Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").WebButton("smnu-01").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").WebButton("smnu-01")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("¿Cómo empeño?").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("¿Cómo empeño?")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Nacional Monte de Piedad").Page("¿Cómo Empeñar? | Nacional").Link("¿QUÉ PUEDO EMPEÑAR?").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("¿Cómo Empeñar? | Nacional").Link("¿QUÉ PUEDO EMPEÑAR?")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Nacional Monte de Piedad").Page("¿Qué puedo empeñar? |").Link("OFERTA PERSONALIZADA").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("¿Qué puedo empeñar? |").Link("OFERTA PERSONALIZADA")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Nacional Monte de Piedad").Page("Oferta Personalizada |").Link("SIMULADOR").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Oferta Personalizada |").Link("SIMULADOR")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Joyas").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Joyas")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebEdit("WebEdit").Set "15000" @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebEdit("WebEdit")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR_2").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR 2")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Empeño Clásico Tienes").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Empeño Clásico Tienes")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("paso3").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("paso3")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR_3").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("CONTINUAR 3")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Sí").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("Sí")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("calculoBtn").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Frame("Frame").WebElement("calculoBtn")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Link("Contacto").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Simulador | Nacional Monte").Link("Contacto")_;_script infofile_;_ZIP::ssf15.xml_;_

Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG")_;_script infofile_;_ZIP::ssf16.xml_;_
 @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte").Link("PREREGISTRO")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte").Link("Cultura Financiera").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte").Link("Cultura Financiera")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte_2").Link("Conócelas aquí").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte 2").Link("Conócelas aquí")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Nacional Monte de Piedad").Page("Porque el empeño es la").Link("Conoce los pasos para").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Porque el empeño es la").Link("Conoce los pasos para")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Nacional Monte de Piedad").Page("Empeño Clásico | Nacional").Link("Refrendo").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Empeño Clásico | Nacional").Link("Refrendo")_;_script infofile_;_ZIP::ssf22.xml_;_

Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Nacional Monte de Piedad").Link("BLOG")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte").Link("Ahorro").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte").Link("Ahorro")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte_3").Link("Autos").Click @@ hightlight id_;_Browser("Nacional Monte de Piedad").Page("Blog | Nacional Monte 3").Link("Autos")_;_script infofile_;_ZIP::ssf25.xml_;_

'Se detecta defecto defect #1025
